# Generated by Django 4.0.3 on 2022-06-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
