# Generated by Django 4.0.3 on 2022-06-08 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts_app', '0002_alter_post_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Posts_app.post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Posts_app.post')),
            ],
            bases=('Posts_app.post',),
        ),
    ]
